### ISSUE TITLE
FR: Tooltips?

### ISSUE THREAD

**Issue by nqthqn** [artisticat1/nl-syntax-highlighting#10]
When I turned this on I didn't have a mapping in my mind established for each color — so maybe this is NOT worth implementing and instead I should simply use the plugin a bit more.

This is my initial stab at this in my `snippets.css`

```css
.adjective:before {
  content: "adjective";
}

.noun:before {
  content: "noun";
}

.adverb:before {
  content: "adverb";
}

.verb:before {
  content: "verb";
}

.conjunction:before {
  content: "conjunction";
}

.adjective:before,
.noun:before,
.adverb:before,
.verb:before,
.conjunction:before {
  position: absolute;
  top: -24px;
  left: 0;
  width: auto;
  padding: 2px 8px;
  border-radius: 4px;
  background: #000;
  color: #fff;
  opacity: 0.7;
  text-align: center;
  display: none;
}

.adjective:hover:before,
.noun:hover:before,
.adverb:hover:before,
.verb:hover:before,
.conjunction:hover:before {
  display: block
}
```
